// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./src/components/A/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Tree: typeof import('./src/components/Tree/index.vue')['default']
  }
}

export { }
